=== austinvernsonger/tjchemical/TjChemicalWeb/_System/Config.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!--
    Example
    <SundayMaker>
        <DBProvider TYPE="SQLDB" MaxConn="1000">
            <DBName>ExampleDB</DBName>
            <DBPath>ExampleURL or IP</DBPath>
            <UserName>sa</UserName>
            <Password>pwd</Password>
        </DBProvider>
        
        <ConnectionString TYPE="SQLDB">Provider Microsoft SQL Server...</ConnectionString>
        
        <FileLocate MaxSize="10000" MaxCacheSize="1000">
            <Title>Error</Title>
            <Path>/Logs/err.log</Path>
        </FileLocate>
        
        <CacheReg>
            <Cache Id="asdjag8wetsdasu5rqwha">
                <Name>News</Name>
            </Cache>
        </CacheReg>
        
        <Page Code="404">
            <Path>/System/404.aspx</Path>
        </Page>
    </SundayMaker>
-->

<!ELEMENT SundayMaker (DBProvider+,ConnectString+,CacheReg*,(FileLocate|Page)*)>

<!--First Level-->
<!ELEMENT DBProvider    (DBName,DBPath,UserName,Password)>
<!ELEMENT ConnectString (#PCDATA)>
<!ELEMENT CacheReg      (Cache*)>
<!ELEMENT FileLocate    (Title,Path)>
<!ELEMENT Page          (Path)>

<!--Second Level-->
<!ELEMENT DBName        (#PCDATA)>
<!ELEMENT DBPath        (#PCDATA)>
<!ELEMENT UserName      (#PCDATA)>
<!ELEMENT Password      (#PCDATA)>

<!ELEMENT String        (#PCDATA)>

<!ELEMENT Cache         (Name)> <!--The name can be used to specified a cache file-->

<!ELEMENT Title         (#PCDATA)>
<!ELEMENT Path          (#PCDATA)>
<!ELEMENT MaxSize       EMPTY>
<!ELEMENT MaxCacheSize  EMPTY>

<!--Third Level-->
<!ELEMENT Name          (#PCDATA)>

<!--Attribute-->
<!ATTLIST DBProvider Name ID #REQUIRED>
<!ATTLIST DBProvider TYPE (OLEDB|SQLDB|ORACLE|MYSQL) #REQUIRED>
<!ATTLIST ConnectString TYPE (OLEDB|SQLDB|ORACLE|MYSQL) #REQUIRED>
<!ATTLIST Cache Id ID #REQUIRED>
<!ATTLIST DBProvider MaxConn CDATA #REQUIRED>
<!ATTLIST FileLocate MaxSize CDATA #REQUIRED>
<!ATTLIST FileLocate MaxCacheSize CDATA #REQUIRED>
<!ATTLIST Page Code CDATA #REQUIRED>

=== austinvernsonger/tjchemical/trunk/TJChemicalWebsite/_System/Config.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--
    This is the configuration file of the database.
    DBName is the database Name
    DBPath is the database file's path
    UserName and password are used to access the database
    Provider shoude be OLEDB or SQLDB or other providers inheirs from DBProvider
    MaxConn is the max connection number the database can provide at one time.
-->

<!DOCTYPE SundayMaker SYSTEM 'Config.dtd'>

<SundayMaker>
    <DBProvider Name='Information' TYPE='SQLDB' MaxConn='500'>
      <DBName>SSE</DBName>
      <DBPath>10.60.43.9</DBPath>
      <UserName>sse_information</UserName>
      <Password>helloworld</Password>
    </DBProvider>
  <DBProvider Name='BasicInfo' TYPE='SQLDB' MaxConn='500'>
    <DBName>SSE</DBName>
    <DBPath>10.60.43.9</DBPath>
    <UserName>sse_basicinfo</UserName>
    <Password>abcd</Password>
  </DBProvider>

  <DBProvider Name='Account' TYPE='SQLDB' MaxConn='500'>
    <DBName>SSE</DBName>
    <DBPath>10.60.43.9</DBPath>
    <UserName>sse_account</UserName>
    <Password>sayhello</Password>
  </DBProvider>

  <DBProvider Name='AlumnusRecord' TYPE='SQLDB' MaxConn='1000'>
    <DBName>SSE</DBName>
    <DBPath>10.60.43.9</DBPath>
    <UserName>sse_graduates</UserName>
    <Password>helloworld</Password>
  </DBProvider>

  <DBProvider Name='Teaching' TYPE='SQLDB' MaxConn='1000'>
    <DBName>SSE</DBName>
    <DBPath>10.60.43.9</DBPath>
    <UserName>sse_teacher</UserName>
    <Password>teacher</Password>
  </DBProvider>

  <DBProvider Name='LabCenter' TYPE='SQLDB' MaxConn='500'>
    <DBName>SSE</DBName>
    <DBPath>10.60.43.9</DBPath>
    <UserName>sse_labcenter</UserName>
    <Password>icore</Password>
  </DBProvider>

  <DBProvider Name='Engineering' TYPE='SQLDB' MaxConn='500'>
    <DBName>SSE</DBName>
    <DBPath>10.60.43.9</DBPath>
    <UserName>sse_mstudent</UserName>
    <Password>mstudent</Password>
  </DBProvider>






  <ConnectString TYPE='SQLDB'>Persist Security Info=True;Initial Catalog=</ConnectString>

    <ConnectString TYPE='OLEDB'>
        ConnectStringHere
    </ConnectString>

    <CacheReg>
        <Cache Id='ManuallyCache1'>
            <Name>TestCache</Name>
        </Cache>
    </CacheReg>

    <FileLocate MaxSize='5000' MaxCacheSize='100'>
        <Title>Log</Title>
        <Path>_System\Log.xml</Path>
    </FileLocate>

    <FileLocate MaxSize='1000' MaxCacheSize='200'>
        <Title>Error</Title>
        <Path>_System\Error.xml</Path>
    </FileLocate>
    
    <Page Code='404'>
        <Path>~\404.aspx</Path>
    </Page>
    <Page Code='500'>
        <Path>~\SystemError.aspx</Path>
    </Page>

</SundayMaker>

=== austinvernsonger/tjchemical/TjChemicalWeb/_System/Config.xml
<?xml version="1.0" encoding="utf-8" ?>

<!--
    This is the configuration file of the database.
    DBName is the database Name
    DBPath is the database file's path
    UserName and password are used to access the database
    Provider shoude be OLEDB or SQLDB or other providers inheirs from DBProvider
    MaxConn is the max connection number the database can provide at one time.
-->

<!DOCTYPE SundayMaker SYSTEM 'Config.dtd'>

<SundayMaker>
  <DBProvider Name="TjMedical" MaxConn="1000" TYPE="SQLDB">
    <DBName>tjmedicine</DBName>
    <DBPath>10.60.43.9</DBPath>
    <UserName>tjMdc_student</UserName>
    <Password>1234</Password>
  </DBProvider>
  
   <ConnectString TYPE='SQLDB'>Persist Security Info=True;Initial Catalog=</ConnectString>

    <ConnectString TYPE='OLEDB'>
        ConnectStringHere
    </ConnectString>

    <CacheReg>
        <Cache Id='ManuallyCache1'>
            <Name>TestCache</Name>
        </Cache>
    </CacheReg>

    <FileLocate MaxSize='5000' MaxCacheSize='100'>
        <Title>Log</Title>
        <Path>_System\Log.xml</Path>
    </FileLocate>

    <FileLocate MaxSize='1000' MaxCacheSize='200'>
        <Title>Error</Title>
        <Path>_System\Error.xml</Path>
    </FileLocate>
    
    <Page Code='404'>
        <Path>~\404.aspx</Path>
    </Page>
    <Page Code='500'>
        <Path>~\SystemError.aspx</Path>
    </Page>

</SundayMaker>
